#程序启动的端口号
listenPort: 3001
#生成的封面高度值，宽度自动。
coverHeight: 650
#相册的目录地址，相对于当前执行文件
photoAlbumPath: ./PhotoAlbum
#网站名字
siteName: XuSenLin 的摄影集
# html 关键字 描述
htmlKeywords: XuSenLin photoAlbum
htmlDescription : XuSenLin photoAlbum Web

